[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/r/:shortcode"
  to = "/.netlify/functions/redirector?code=:shortcode"
  status = 200
  
[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/**"]