[build]
  functions = "netlify/functions"
  publish = "public"
  
[[redirects]]
  from = "/pay/*"
  to = "/.netlify/functions/pay"
  status = 200

[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/razorpay/**"]